# Generated by Django 4.2.6 on 2023-11-12 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='', max_length=200)),
                ('article_url', models.CharField(default='https://finance.naver.com', max_length=300)),
                ('crawling_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TradingVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, verbose_name='순위')),
                ('name', models.CharField(default='없음', max_length=100, verbose_name='종목명')),
                ('current_price', models.IntegerField(default=0, verbose_name='현재가')),
                ('price_change', models.IntegerField(default=0, verbose_name='전일비')),
                ('percent_change', models.CharField(default='0%', max_length=100, verbose_name='등락률')),
                ('volume', models.BigIntegerField(default=0, verbose_name='거래량')),
                ('prev_volume', models.BigIntegerField(default=0, verbose_name='전일거래량')),
                ('market_cap', models.IntegerField(default=0, verbose_name='시가총액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시간')),
            ],
        ),
    ]
