# Generated by Django 4.2.6 on 2023-11-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingvolume',
            old_name='name',
            new_name='stock_name',
        ),
    ]
