# Generated by Django 4.2.6 on 2023-11-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingvolume',
            name='previous_close_price',
        ),
        migrations.RemoveField(
            model_name='tradingvolume',
            name='stock_name',
        ),
        migrations.RemoveField(
            model_name='tradingvolume',
            name='time',
        ),
        migrations.RemoveField(
            model_name='tradingvolume',
            name='volume_increase_rate',
        ),
        migrations.AddField(
            model_name='tradingvolume',
            name='market_cap',
            field=models.IntegerField(default=0, verbose_name='시가총액'),
        ),
        migrations.AddField(
            model_name='tradingvolume',
            name='name',
            field=models.CharField(default='없음', max_length=100, verbose_name='종목명'),
        ),
        migrations.AddField(
            model_name='tradingvolume',
            name='percent_change',
            field=models.CharField(default='0%', max_length=100, verbose_name='등락률'),
        ),
        migrations.AddField(
            model_name='tradingvolume',
            name='prev_volume',
            field=models.BigIntegerField(default=0, verbose_name='전일거래량'),
        ),
        migrations.AddField(
            model_name='tradingvolume',
            name='price_change',
            field=models.IntegerField(default=0, verbose_name='전일비'),
        ),
        migrations.AddField(
            model_name='tradingvolume',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='순위'),
        ),
        migrations.AddField(
            model_name='tradingvolume',
            name='volume',
            field=models.BigIntegerField(default=0, verbose_name='거래량'),
        ),
        migrations.AlterField(
            model_name='tradingvolume',
            name='current_price',
            field=models.IntegerField(default=0, verbose_name='현재가'),
        ),
    ]
