# Generated by Django 4.2.6 on 2023-11-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='crawling_time',
        ),
        migrations.AddField(
            model_name='article',
            name='article_url',
            field=models.CharField(default='https://finance.naver.com', max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(default='', max_length=200),
        ),
    ]
