# Generated by Django 4.2.6 on 2023-11-10 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_tradingvolume_previous_close_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingvolume',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시간'),
        ),
    ]
