# Generated by Django 4.2.6 on 2023-11-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_tradingvolume_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
