# Generated by Django 4.2.6 on 2023-11-10 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_article_crawling_time_article_article_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='crawling_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
