# Generated by Django 4.2.6 on 2023-11-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_stockprice_rank_alter_stockprice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='rank',
        ),
    ]
