# Generated by Django 4.2.6 on 2023-11-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tradingvolume_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingvolume',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='시간'),
        ),
    ]
