# Generated by Django 4.2.6 on 2023-11-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_stockprice_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
