# Generated by Django 4.2.6 on 2023-11-10 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tradingvolume_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_url',
            field=models.CharField(default='https://finance.naver.com', max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='crawling_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tradingvolume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='시간'),
        ),
    ]
